version: "3"
services:
  consumer:
    image: tahasildarrashid/currency-conversion1.1:latest
    ports:
      - "8081:8081"
    networks:
      - consumer-producer
    depends_on:
      - producer
  producer:
    image: tahasildarrashid/currency-exchange:1.1
    ports:
      - "8080:8080"
    networks:
      - consumer-producer
networks:
  consumer-producer:

