spring:
    application:
        name: client1
    config:
        import: optional:configserver:http://localhost:8888
server:
    port: 8081

management:
    endpoint:
        web:
            exposure:
                include: "*"

app:
    name: default config app1